import { GoogleGenAI, Modality } from "@google/genai";
import { fileToBase64, fileToGenerativePart } from '../utils/fileUtils';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    // In a real app, you might want to handle this more gracefully.
    // For this environment, we assume API_KEY is always present.
    console.warn("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

export const generatePfp = async (faceImageFile: File, overlayImageFile: File): Promise<string> => {
    try {
        const faceImagePart = await fileToGenerativePart(faceImageFile);
        const overlayImagePart = await fileToGenerativePart(overlayImageFile);

        const prompt = "Take the first image, which is a person's face. Take the second image, which is a pair of glasses or a mask with a transparent background. Intelligently detect the correct position and size on the face (e.g., eyes for glasses, general face area for a mask) and overlay the second image onto the first. Ensure the overlay blends naturally. Output only the final merged image.";

        const result = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [
                    faceImagePart,
                    overlayImagePart,
                    { text: prompt },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });
        
        const firstPart = result.candidates?.[0]?.content?.parts[0];
        
        if (firstPart && firstPart.inlineData) {
            const { mimeType, data } = firstPart.inlineData;
            return `data:${mimeType};base64,${data}`;
        } else {
            throw new Error("No image was generated by the API. The response might have been blocked.");
        }

    } catch (error) {
        console.error("Error calling Gemini API:", error);
        throw new Error("Failed to generate PFP. The AI model might be unavailable or the request was invalid.");
    }
};
